# Generated by Django 3.2.9 on 2021-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
