# Generated by Django 3.2.9 on 2021-11-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_marks_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='studentclass',
            old_name='classes',
            new_name='grade',
        ),
    ]
